import importlib.util
import logging
import os
import subprocess
import re
from contextlib import contextmanager
from subprocess import run
from pathlib import Path
from time import sleep

from playwright.sync_api import Playwright, sync_playwright, expect
from playwright._impl._errors import TimeoutError, Error

HEADLESS=True

LOG_LEVEL = logging.DEBUG

ACCEPT_TEXT = ["accept", "connect", "agree", "continue", "submit", "internet", "access", "online"]
EMAIL_TEXT = ["email"]
PASSWORD_TEXT = ["password"]
NAME_TEXT = ["name"]

logger = logging.getLogger(__name__)

@contextmanager
def WebDriver():
    driver = None
    try:
        with sync_playwright() as playwright:
            driver = playwright
            yield playwright
    except Exception as e:
        logger.error(e)
        logger.info("""If on Pi, try: 
        playwright install-deps
        playwright install webkit""")
        raise

class CaptivePortalNavigator:
    def __init__(self, playwright=None):
        if playwright is None:
            with WebDriver() as p:
                self.playwright = p
        else:
            self.playwright = playwright

    def navigate(self, portal=None):
        """
        Automatically navigate captive portal, trying a variety of common flows
        """
        
        browser = self.playwright.webkit.launch(headless=HEADLESS)
        context = browser.new_context(ignore_https_errors=True)
        self.page = context.new_page()
        
        try:
            script_success = self._navigate_script()
            if not script_success:
                self._navigate_portal(portal)
        finally:
            context.close()
            browser.close()

    def _navigate_portal(self, portal):
        """
        Automatically navigate captive portal with a known url, trying a variety of common flows
        """

        self.page.goto(portal, wait_until="networkidle")

        if LOG_LEVEL == logging.DEBUG:
            self.page.screenshot(path="captive_portal.png")
            logger.debug("Before Script")
            logger.debug(self.page.content())
        # Simple algorithm:
        #    1. Look for and tick any checkboxes
        #    2. Look for and fill any text inputs with "name" or "email" in the placeholder or label
        #    3. Look for and click any buttons with "accept" or "connect" in the text
        #    4. Profit
        if __name__ == "__main__":
            input("Page loaded")
        self._check_boxes()
        if __name__ == "__main__":
            input("Boxes checked")
        self._fill_inputs()
        if __name__ == "__main__":
            input("Inputs filled")
        self._click_buttons()
        if __name__ == "__main__":
            input("Buttons clicked")
            
        if LOG_LEVEL == logging.DEBUG:
            logger.debug("After Script")
            logger.debug(self.page.content())
            self.page.screenshot(path="captive_portal_redirect.png")
            input("Debug breakpoint. Press enter to continue or ctrl-C to exit")

    def _navigate_script(self):
        """
        Runner for scripts generated by Playwright Codegen

        Generate the script by running `python codegen.py`
        """
        def get_active_ssid() -> str:
            """Gets the currently connected SSID via your nmcli pipeline."""
            try:
                cmd = "nmcli -t -f ACTIVE,SSID dev wifi | awk -F: '$1==\"yes\"{print $2; exit}'"
                return subprocess.check_output(cmd, shell=True, text=True).strip()
            except Exception as e:
                print(f"Error checking network: {e}")
                raise

        def find_script_for_ssid(ssid: str) -> Path | None:
            """Scans the script directory to find a module matching the active SSID."""
            script_dir = Path("Login Scripts") / "User"
            if not script_dir.exists():
                return None

            # Scan all python files in the directory
            for script_path in script_dir.glob("*.py"):
                try:
                    # Dynamically look inside the module without fully mounting or running its functions
                    spec = importlib.util.spec_from_file_location("temp_mod", script_path)
                    mod = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(mod)
                    
                    # Check if our custom metadata match variable exists and aligns
                    if getattr(mod, "ASSOCIATED_SSID", None) == ssid:
                        return script_path
                except Exception:
                    raise
                    
            return None
            
        current_ssid = get_active_ssid()
        if not current_ssid:
            logger.error("Not connected to any Wi-Fi network.")
            return False

        logger.debug(f"Current SSID: {current_ssid}")
        matching_script = find_script_for_ssid(current_ssid)

        if not matching_script:
            logger.warning(f"No login automation found matching SSID: '{current_ssid}'")
            return False

        logger.debug(f"Found matching automation script: {matching_script.name}")

        try:
            # Re-load the specific module cleanly to execute the play sequence
            spec = importlib.util.spec_from_file_location("portal_flow", matching_script)
            portal_flow = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(portal_flow)
                    
            logger.info("Executing portal login automation flow...")
            portal_flow.execute_flow(self.page)
            logger.info("Complete!")
        except Exception as e:
            logger.error(f"Automation runtime crash encountered: {e}")
            raise
                
        return True

    def _check_boxes(self):
        check_boxes = self.page.get_by_role("checkbox")
        radio_buttons = self.page.get_by_role("radio")
        locators = []
        if check_boxes is not None:
            locators.extend(check_boxes.all())
        if radio_buttons is not None:
            locators.extend(radio_buttons.all())

        for loc in locators:
            if not loc.is_checked():
                loc.click(timeout=500)

    def _fill_inputs(self):
        email_inputs = self.page.get_by_role("textbox", name=re.compile("|".join(EMAIL_TEXT), re.IGNORECASE))
        name_inputs = self.page.get_by_role("textbox", name=re.compile("|".join(NAME_TEXT), re.IGNORECASE))
        password_inputs = self.page.get_by_role("textbox", name=re.compile("|".join(PASSWORD_TEXT), re.IGNORECASE))
        all_inputs = self.page.get_by_role("textbox")
        for loc in all_inputs.all():
            try:
                if loc in email_inputs.all():
                    loc.fill("email@domain.com", timeout=500)
                elif loc in name_inputs.all():
                    loc.fill("name", timeout=500)
                elif loc in password_inputs.all():
                    pass # assume no password (and fail if there is one)
                else:
                    loc.fill("lorem ipsum dolor", timeout=500)
            except (TimeoutError, Error):
                pass # expected, e.g. if element is not interactable

    def _click_buttons(self):
        links = self.page.get_by_role("link", name=re.compile("|".join(ACCEPT_TEXT), re.IGNORECASE))
        buttons = self.page.get_by_role("button", name=re.compile("|".join(ACCEPT_TEXT), re.IGNORECASE)) 
        locators = []
        if links is not None:
            locators.extend(links.all())
        if buttons is not None:
            locators.extend(buttons.all())
        try:
            for loc in locators:
                logger.debug(f"Clicking locator: {loc.inner_text()}")
                loc.click(timeout=500)
        except TimeoutError:
            logger.debug("Click timeout")
            pass # expected if the first locator works


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    logger = logging.getLogger(__name__)
    with WebDriver() as driver:
        navigator = CaptivePortalNavigator(driver)
        navigator.navigate(portal="file:///" + os.path.join(os.getcwd(), "test", "aandw.html"))
        #navigator.navigate(portal="https://www.selenium.dev/selenium/web/web-form.html")
        input("press enter to exit")
